sudo: false
language: node_js
node_js:
- 0.10.32
before_script:
- npm install -g bower grunt-cli
- bower install
script:
- grunt test:client
- grunt test:server
- grunt jshint
- grunt lintspaces
- "./node_modules/.bin/karma start --single-run --browsers PhantomJS karma.conf.js"
services: mongodb
